### ISSUE TITLE
Object 'res' not found

### ISSUE THREAD

**Issue by SandipanHaldar** [imbhe/OSiUAL#1]
`df <- bind_cols(file = rep(file, nrow(res)), res)`  line 71 of run_experiments.R does not define res. So I am getting an error `Object res not found `

**Comment by imbhe** [comment]
Did you run the entire script? res included in the .RData workspaces created on line 56 (when calling the al.R function) and loaded on line 70. To save space, these .RData are not included in the git repo. Thus, line 60 and on will only run properly if you first run the preceding lines of code. However, all that happens from line 60 is that the results of individual runs of the active learning algorithms are summarised as means and medians into Results/summary_results.RData, which then is used in Rscript/tables_and_figures.R to generate the tables and figures presented in the paper. Hope that this helps and please let me know otherwise.

**Comment by SandipanHaldar** [comment]
Hi,
The al.R is getting executed without any issue and the value of exec is 1
(I printed that). In spite of that, the code is getting stuck on line 71.
[image: Screenshot from 2021-02-23 09-29-48.png]
https://drive.google.com/file/d/1irRXmJlBujaVFC8EmhGveqSLLRmB8ayF/view?usp=drivesdk
Here's a screenshot of my terminal. I have set n_final=25, n_cores=1,
n_rep=1 (for super-fast execution).  In al.R after line 242, I have
inserted *print("SAVING RES!!")* and *print(outfile). *The series of 1  are
the printed value of exec inserted in run_experiments.R on after line 56. I
think the error is due to not defining res in run_experiments.R, but
I cant fix it.

Thanks.

**Comment by imbhe** [comment]
I can't see the screenshot. Could you try sending it again?

**Comment by SandipanHaldar** [comment]
I added a drive link in my last comment. Please see that.

**Comment by imbhe** [comment]
Thanks. I think I have spotted the error. It seems like the foreach-loop on line 109 is evaluated as an ordinary for-loop when running on a single core, which then makes al.R terminate prematurely on line 216. Try running the script with n_cores = 2.

**Comment by imbhe** [comment]
An alternative solution would be to change 
`# return(1) # Return value, foreach.`
on line 216 in al.R to
`val <- 1 # Return value, foreach.`
Please let me know if this solves the problem so that I can update the code and mark the issue as closed.

**Comment by imbhe** [comment]
I have updated the code, it should now execute properly also when running on a single core. Closing the issue.
